// Generated by https://quicktype.io

import { Member } from "src/app/members/interfaces/member.interface";

export interface Auth {
  jwt:     string;
  details: null;
  user:    Member;
}

export interface Role {
  id:          number;
  name:        string;
  description: string;
  isActive:    boolean;
  createdAt:   string;
}